on: push

jobs:
  tests:
    runs-on: ubuntu-latest
    name: Testing with Laravel ${{ matrix.laravel }} and PHP ${{ matrix.php }}
    strategy:
        matrix:
            php: [7.2.5, 7.3, 7.4]
            laravel: [5.6.*, 5.7.*, 5.8.*, ^6.0, ^7.0, ^8.0]
            exclude:
                - laravel: ^8.0
                  php: 7.2.5
    steps:
      - uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip
          coverage: none

      - name: Install Composer dependencies
        run: |
            composer require "laravel/framework:${{ matrix.laravel }}" --no-interaction --no-update
            composer update --prefer-dist --no-interaction --no-ansi --no-progress

      - name: Execute tests
        run: |
          vendor/bin/phpcs
          vendor/bin/phpunit
